import { SituacaoDoProcesso } from "app/modules/acervo/model/enums/situacaoDoProcesso.enum";
import { TipoDoProcesso } from "app/modules/acervo/model/enums/tipoDoProcesso.enum";
import { Processo } from "app/modules/acervo/model/interfaces/processo.interface";
import { SessaoJulgamento } from "app/modules/acervo/model/interfaces/sessao-julgamento.interface";

import { capitulo } from "../capitulo/data";
import { ministro } from '../ministro/data';

export function getJulgamentos() {
    if(sessionStorage.getItem('julgamentos') == null)
      sessionStorage.setItem('julgamentos', JSON.stringify(julgamentos));
    return JSON.parse(sessionStorage.getItem('julgamentos'));
  };
export const julgamentos: SessaoJulgamento[] = [
  {
    id: 0,
    numero: 1000,
    ano: 2021,
    colegiado: 'Primeira turma',
    tipo: 'ORDINARIA',
    categoria: 'REPERCUSSAO_GERAL',
    modalidade: 'VIRTUAL',
    data_inicio: '2016-08-29T09:12:33.001Z',
    data_fim: '2016-08-30T09:12:33.001Z',
    situacao: 'ABERTA',
    secretario: {
      id: 0,
      nome: 'Beatriz Cunha',
    },
    presidencia: ministro[10],
  },
  {
    ano: 2021,
    id: 1,
    numero: 1,
    colegiado: 'Primeira Turma',
    modalidade: 'Virtual',
    categoria: 'Judicial',
    tipo: 'Ordinária',
    data_inicio: '2021-06-29T09:12:33.001Z',
    data_fim: '2021-12-29T09:12:33.001Z',
    situacao: 'ABERTA',
    secretario: {
      id: 0,
      nome: 'Beatriz Cunha',
    },
    presidencia: ministro[0],
  },
  {
    ano: 2021,
    id: 2,
    numero: 2,
    colegiado: 'Primeira Turma',
    modalidade: 'Virtual',
    categoria: 'Judicial',
    tipo: 'Ordinária',
    data_inicio: '2021-06-29T09:12:33.001Z',
    data_fim: '2021-12-29T09:12:33.001Z',
    situacao: 'ABERTA',
    secretario: {
      id: 0,
      nome: 'Beatriz Cunha',
    },
    presidencia: ministro[0],
  },
  {
    ano: 2021,
    id: 3,
    numero: 3,
    colegiado: 'Segunda Turma',
    modalidade: 'Virtual',
    categoria: 'Judicial',
    tipo: 'Ordinária',
    data_inicio: '2021-04-29T09:12:33.001Z',
    data_fim: '2021-11-29T09:12:33.001Z',
    situacao: 'ABERTA',
    secretario: {
      id: 0,
      nome: 'Beatriz Cunha',
    },
    presidencia: ministro[0],
  },
  {
    ano: 2021,
    id: 4,
    numero: 4,
    colegiado: 'Segunda Turma',
    modalidade: 'Virtual',
    categoria: 'Judicial',
    tipo: 'Ordinária',
    data_inicio: '2021-04-29T09:12:33.001Z',
    data_fim: '2021-11-29T09:12:33.001Z',
    situacao: 'ABERTA',
    secretario: {
      id: 0,
      nome: 'Beatriz Cunha',
    },
    presidencia: ministro[0],
  },
  {
    ano: 2021,
    id: 5,
    numero: 5,
    colegiado: 'Segunda Turma',
    modalidade: 'Virtual',
    categoria: 'Judicial',
    tipo: 'Ordinária',
    data_inicio: '2021-03-29T09:12:33.001Z',
    data_fim: '2021-10-29T09:12:33.001Z',
    situacao: 'ABERTA',
    secretario: {
      id: 0,
      nome: 'Beatriz Cunha',
    },
    presidencia: ministro[0],
  },
  {
    ano: 2021,
    id: 6,
    numero: 6,
    colegiado: 'Segunda Turma',
    modalidade: 'Virtual',
    categoria: 'Judicial',
    tipo: 'Ordinária',
    data_inicio: '2021-03-29T09:12:33.001Z',
    data_fim: '2021-10-29T09:12:33.001Z',
    situacao: 'ABERTA',
    secretario: {
      id: 0,
      nome: 'Beatriz Cunha',
    },
    presidencia: ministro[0],
  },
  {
    ano: 2021,
    id: 7,
    numero: 7,
    colegiado: 'Segunda Turma',
    modalidade: 'Virtual',
    categoria: 'Judicial',
    tipo: 'Ordinária',
    data_inicio: '2021-03-29T09:12:33.001Z',
    data_fim: '2021-10-29T09:12:33.001Z',
    situacao: 'ABERTA',
    secretario: {
      id: 0,
      nome: 'Beatriz Cunha',
    },
    presidencia: ministro[0],
  },
  {
    ano: 2021,
    id: 8,
    numero: 8,
    colegiado: 'Pleno',
    modalidade: 'Virtual',
    categoria: 'Judicial',
    tipo: 'Ordinária',
    data_inicio: '2021-07-29T09:12:33.001Z',
    data_fim: '2021-10-29T09:12:33.001Z',
    situacao: 'ABERTA',
    secretario: {
      id: 0,
      nome: 'Beatriz Cunha',
    },
    presidencia: ministro[0],
  },
  {
    ano: 2021,
    id: 9,
    numero: 9,
    colegiado: 'Pleno',
    modalidade: 'Virtual',
    categoria: 'Judicial',
    tipo: 'Ordinária',
    data_inicio: '2021-01-29T09:12:33.001Z',
    data_fim: '2021-12-29T09:12:33.001Z',
    situacao: 'ABERTA',
    secretario: {
      id: 0,
      nome: 'Beatriz Cunha',
    },
    presidencia: ministro[0],
  },
  {
    ano: 2021,
    id: 10,
    numero: 10,
    colegiado: 'Pleno',
    modalidade: 'Virtual',
    categoria: 'Judicial',
    tipo: 'Ordinária',
    data_inicio: '2021-09-29T09:12:33.001Z',
    data_fim: '2021-12-29T09:12:33.001Z',
    situacao: 'ABERTA',
    secretario: {
      id: 0,
      nome: 'Beatriz Cunha',
    },
    presidencia: ministro[0],
  },
  {
    ano: 2021,
    id: 11,
    numero: 11,
    colegiado: 'Primeira Turma',
    modalidade: 'Presencial',
    categoria: 'Judicial',
    tipo: 'Ordinária',
    data_inicio: '2021-06-29T09:12:33.001Z',
    data_fim: '2021-12-29T09:12:33.001Z',
    situacao: 'ABERTA',
    secretario: {
      id: 0,
      nome: 'Beatriz Cunha',
    },
    presidencia: ministro[0],
  },
  {
    ano: 2021,
    id: 12,
    numero: 12,
    colegiado: 'Primeira Turma',
    modalidade: 'Presencial',
    categoria: 'Judicial',
    tipo: 'Ordinária',
    data_inicio: '2021-06-29T09:12:33.001Z',
    data_fim: '2021-12-29T09:12:33.001Z',
    situacao: 'ABERTA',
    secretario: {
      id: 0,
      nome: 'Beatriz Cunha',
    },
    presidencia: ministro[0],
  },
  {
    ano: 2021,
    id: 13,
    numero: 13,
    colegiado: 'Segunda Turma',
    modalidade: 'Presencial',
    categoria: 'Judicial',
    tipo: 'Ordinária',
    data_inicio: '2021-04-29T09:12:33.001Z',
    data_fim: '2021-11-29T09:12:33.001Z',
    situacao: 'ABERTA',
    secretario: {
      id: 0,
      nome: 'Beatriz Cunha',
    },
    presidencia: ministro[0],
  },
  {
    ano: 2021,
    id: 14,
    numero: 14,
    colegiado: 'Segunda Turma',
    modalidade: 'Presencial',
    categoria: 'Judicial',
    tipo: 'Ordinária',
    data_inicio: '2021-04-29T09:12:33.001Z',
    data_fim: '2021-11-29T09:12:33.001Z',
    situacao: 'ABERTA',
    secretario: {
      id: 0,
      nome: 'Beatriz Cunha',
    },
    presidencia: ministro[0],
  },
  {
    ano: 2021,
    id: 15,
    numero: 15,
    colegiado: 'Pleno',
    modalidade: 'Presencial',
    categoria: 'Judicial',
    tipo: 'Ordinária',
    data_inicio: '2021-03-29T09:12:33.001Z',
    data_fim: '2021-10-29T09:12:33.001Z',
    situacao: 'ABERTA',
    secretario: {
      id: 0,
      nome: 'Beatriz Cunha',
    },
    presidencia: ministro[0],
  },
  {
    ano: 2021,
    id: 16,
    numero: 16,
    colegiado: 'Pleno',
    modalidade: 'Presencial',
    categoria: 'Judicial',
    tipo: 'Ordinária',
    data_inicio: '2021-03-29T09:12:33.001Z',
    data_fim: '2021-10-29T09:12:33.001Z',
    situacao: 'ABERTA',
    secretario: {
      id: 0,
      nome: 'Beatriz Cunha',
    },
    presidencia: ministro[0],
  },
];

export const processos: Processo[] = [
  {
    id: 123455,
    ementa: "Sessão de julgamento extraordinária para tratar da divisão de terras.",
    lista: [{
      descricao: "Semelhante a ADI 100",
      id: 123445,
      publica: false
    }],
    classe: "ADI",
    numero: 100,
    nome: "Embargo de declaração",
    abreviacao: '',
    situacao: SituacaoDoProcesso.Pautado,
    tipo: TipoDoProcesso.Merito,
    capitulos: [
      capitulo[1],
    ],
    ministros_impedidos: [],
    ministros_suspeitos: [],
  },

  {
    id: 123455,
    ementa: "Sessão de julgamento extraordinária para tratar da divisão de terras.",
    lista: [{
      descricao: "Semelhante a ADI 100",
      id: 123445,
      gestor: {
          numero: 19,
          criacao: '2021-08-02T03:00:00.000Z',
      },
      publica: false
    }],
    classe: 'ADI',
    numero: 100,
    nome: 'Embargo de declaração',
    abreviacao: '',
    situacao: SituacaoDoProcesso.Pautado,
    tipo: TipoDoProcesso.Merito,
    relator: ministro[10],
    redator: ministro[10],
    capitulos: [
      capitulo[1],
    ],
    ministros_impedidos: [],
    ministros_suspeitos: [],
  },

  {
    id: 123455,
    ementa: 'Sessão de julgamento extraordinária para tratar da divisão de terras.',
    lista: [{
      descricao: 'Semelhante a ADI 100',
      id: 123445,
      gestor: {
          numero: 19,
          criacao: '2021-08-02T03:00:00.000Z',
      },
      publica: false
    }],
    classe: 'ADI',
    numero: 100,
    nome: "Embargo de declaração",
    abreviacao: '',
    situacao: SituacaoDoProcesso.Pautado,
    tipo: TipoDoProcesso.Merito,
    capitulos: [
      capitulo[1],
    ],
    ministros_impedidos: [],
    ministros_suspeitos: [],
  },
]
